"use client";
import { useEffect, useState, Suspense } from "react";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useSearchParams } from 'next/navigation';

function SuccessContent() {
  const searchParams = useSearchParams();
  const labelUrl = searchParams.get('labelUrl');
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  if (!isClient) return null;

  return (
    <>
      <div className="breadcrumb-section breadcrumb-bg">
        <div className="container">
          <div className="row">
            <div className="col-lg-8 offset-lg-2 text-center">
              <div className="breadcrumb-text">
                <p>Order Confirmed</p>
                <h1>Thank You!</h1>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="mt-150 mb-150 text-center">
        <div className="container">
          <div className="row">
            <div className="col-lg-8 offset-lg-2 text-center">
              <h2>Your order has been placed successfully.</h2>
              <p className="mt-4">We are processing your handcrafted treasures. A confirmation has been sent to your email.</p>
              
              {labelUrl && (
                <div className="mt-5 p-4" style={{border: '1px dashed #F28123', borderRadius: '8px', background: '#fcfcfc'}}>
                  <h4>Vendor / Admin Actions</h4>
                  <p>A shipping label has been automatically generated by Shiprocket.</p>
                  <a href={decodeURIComponent(labelUrl)} target="_blank" rel="noopener noreferrer" className="boxed-btn mt-3">Download Shipping Label</a>
                  <p className="mt-3"><small>Share this label PDF via WhatsApp with the artisan for fulfillment.</small></p>
                </div>
              )}

              <div className="mt-5">
                <a href="/shop" className="boxed-btn black">Continue Shopping</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default function Success() {
  return (
    <>
      <Navbar />
      <Suspense fallback={<div>Loading...</div>}>
        <SuccessContent />
      </Suspense>
      <Footer />
    </>
  );
}
